config/routes.rb
Rails.application.routes.draw do
  resources :users

  resources :comments do
    resources :comments
  end
 
  resources :posts do
    resources :comments
  end
  resources :sessions
   
  root 'posts#index'
  get 'signup', to: 'users#new', as: 'signup'

  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'

end

app/models/comment.rb
class Comment < ActiveRecord::Base
	belongs_to :user
	belongs_to :post
	belongs_to :comment, :dependent => :destroy
	belongs_to :commentable, :polymorphic => true
	has_many :comments, :as => :commentable, :dependent => :destroy


	def post
		return @post if defined?(@post)
		@post = commentable.is_a?(Post) ? commentable : commentable.post
 # if “commentable” (the parent object) is a post, return that. Otherwise, call this same method on the parent, which will in turn check if *it* is a Post, and so on.
end

end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :user
  has_many :comments, :as => :commentable, :dependent => :destroy
end

app/models/user.rb
class User < ActiveRecord::Base
	has_attached_file :avatar, :styles => { :medium => "300*300", :thumb => "100*100", :com => "64*64" }
	has_many :posts
	has_secure_password

	validates :email, presence: true, uniqueness: true
	validates :name, presence: :true	
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  private
  def current_user
  	if session[:user_id]
  		@current_user ||= User.find(session[:user_id])
  	end
  end
  helper_method :current_user

  def authenticate_user!
  	redirect_to login_path unless current_user
  end


end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	before_filter :get_parent

	def new 
		@comment = @parent.comments.build
	end

	def create
		@comment = @parent.comments.build(comment_params.merge(:user_id => current_user.id))

		if @comment.save
			redirect_to post_path(@comment.post), notice: 'Thank you for your comment!'
		else
			render :new
		end
	end

	def edit
		@comment = Comment.find(params[:id])
	end

	def destroy
		@comment = Comment.find(params[:id])
		@comment.destroy
		redirect_to posts_path
	end

		def update
		@comment = Comment.find(params[:id])
		@comment.update(comment_params)

		flash.notice = "Comment Updated!"


		redirect_to comment_path(@comment)
	end

	protected

	def get_parent
		@parent = Post.find_by_id(params[:post_id]) if params[:post_id]
		@parent = Comment.find_by_id(params[:comment_id]) if params[:comment_id]
		
		redirect_to root_path unless defined?(@parent)
	end

	private

	def comment_params
		params.require(:comment).permit(:body)
	end



end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
	
	before_action :authenticate_user!, :except => [:index]

	def index
		@posts = Post.all
	end

	def show
		@post = Post.find(params[:id])
	end

	def new
		@post = Post.new
	end

	def create
		@post = Post.new(post_params.merge(:user_id => current_user.id))

		if @post.save
			redirect_to posts_path, notice: "Your post was created successfully."
		else
			render :action => :new
		end
	end
	
	def destroy
		@post = Post.find(params[:id])
		@post.destroy

		redirect_to posts_path
	end


	def edit
		@post = Post.find(params[:id])
	end

	def update
		@post = Post.find(params[:id])
		@post.update(post_params)

		flash.notice = "Post '#{@post.title}' Updated!"


		redirect_to post_path(@post)
	end

	private

	def post_params
		params.require(:post).permit(:title, :body)
	end




end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:email])

    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to root_url, notice: "Log in successful!"
    else
      flash.now.alert = "Invalid email or password"
      render "new"
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url, notice: "Log out successful!"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	def new
		@user = User.new
	end

	def create
		@user = User.new(user_params)
		if @user.save
			redirect_to root_url, notice: "Welcome to site!"
		else
			render "new"
		end
	end

	private

	def user_params
		params.require(:user).permit(:name, :email, :password, :password_confirmation, :avatar)
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/_comment.html.erb
<li class="comment">

  <table>
    <tr>
      <td rowspan="2"> <%= image_tag comment.user.avatar.url(:com) %> </td>
      <th>Comment by <%= comment.user.name %></th>
    </tr>
    <tr>
      <th><%= comment.created_at%></th>
    </tr>
  </table>


  <div class="body">
    <%= comment.body %>
  </div>
  
  <p><%= link_to 'Add a Reply', new_comment_comment_path(comment), class: "btn btn-primary btn-sm" %></p>

  <p><%= if current_user.id == comment.user_id then link_to 'Edit', edit_comment_comment_path(comment, comment) end %> <%=if current_user.id == comment.user_id then "or " end%><%= if current_user.id == comment.user_id then link_to 'Delete', post_comment_path(comment.commentable, comment), :method => :delete end%> </p>

  
  
  <% unless comment.comments.empty? %>
  <ul class="comment_list">
    <%= render :partial => 'comments/comment', :collection => comment.comments %>
  </ul>
  <% end %>
</li>

app/views/comments/_form.html.erb
<%= form_for [@parent, @comment] do |f| %>

<p>
	<%= f.label :body %><br>
	<%= f.text_area :body %>
</p>

<p><%= f.submit %></p>
<% end %>

app/views/comments/edit.html.erb
<h1>Edit comment</h1>
<%= render partial: 'form'%>

app/views/comments/new.html.erb
<h1>Add a Comment</h1>

<%= render partial: 'form'%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
	<title>SuperBlog</title>
	<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
	<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
	<%= csrf_meta_tags %>
</head>
<body>
 <!-- Navigation -->
    <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
        <div class="container">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="/posts">Super Blog</a>
            </div>
            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav">
                    <li>
                        <%= link_to 'New Post', new_post_path %>
                    </li>
                    <li>
                        
                    </li>
                    <li>
                        
                    </li>
                </ul>
            </div>
            <!-- /.navbar-collapse -->
        </div>
        <!-- /.container -->
    </nav>

	<div class="container">
		<% if notice %>
		<div class="alert alert-success"><%= notice %></div>
		<%end%>
		
		<% if alert %>
		<div class="alert alert-danger"><%= alert %></div>
		<%end%>
		<div class="pull-right">
			<% if current_user %>
			<%= link_to 'Log Out', logout_path %>
			<% else %>
			<%= link_to 'Log In', login_path %> or
			<%= link_to 'Sign Up', signup_path %>
			<% end %>
		</div>


		<div>

			<%= yield %>

		</div>

	</div>
</body>
</html>

app/views/posts/_form.html.erb
<%= form_for(@post) do |f| %>
<ul>
  <% @post.errors.full_messages.each do |error| %>
  <li><%= error %></li>
  <% end %>
</ul>
<p>
  <%= f.label :title %><br />
  <%= f.text_field :title, class: "title-area-size" %>
</p>
<p>
  <%= f.label :body %><br />
  <%= f.text_area :body, class: "text-area-size"  %>
</p>
<p>
  <%= f.submit %>
</p>
<% end %>

app/views/posts/edit.html.erb
<h1>Edit Post</h1>

<%= render partial: 'form' %>

app/views/posts/index.html.erb
<!-- Page Content -->
<div class="container">

	<div class="row">

		<!-- Blog Entries Column -->
		<div class="col-md-8">

			<h1 class="page-header">
				All Posts
				<small><p>Add a <%= link_to 'new post', new_post_path %></p></small>
			</h1>

			<ul>
			<div class="panel panel-default">
				<% @posts.each do |post| %>
				<div class="panel-heading"><%= link_to post.title, post_path(post) %></div>
				<!-- <li><%= link_to post.title, post_path(post) %></li> -->
				<div class="panel-body">
				<%= truncate(post.body, length: 100)%>
				
				</div>
			
				<% end %>
			</ul>
			</div>

		</div>
	</div>

	</div>

app/views/posts/new.html.erb
<h1>Add a Post</h1>

<%= render partial: 'form' %>

app/views/posts/show.html.erb
<h1><%= @post.title %></h1>

  <table>
    <tr>
      <td rowspan="2"> <%= image_tag @post.user.avatar.url(:thumb) %> </td>
      <th>Posted By <%= @post.user.name  %></th>
    </tr>
    <tr>
      <th><%= @post.created_at%></th>
    </tr>
  </table>




<div class="body">
	<%= @post.body %>  
</div>

<p>
  <%= if current_user.id == @post.user_id then link_to "delete  ", post_path(@post),method: :delete , data: {confirm: "Really delete the post?"} end%>
  <%=  if current_user.id == @post.user_id then link_to "edit", edit_post_path(@post) end%>
</p>


<h2>Comments</h2>

<p><%= link_to 'Add a Comment', new_post_comment_path(@post), class: "btn btn-primary" %></p>

<ul class="comment_list">
	<%= render :partial => 'comments/comment', :collection => @post.comments %>
</ul>

<p><%= link_to "<< Back to Posts List", posts_path %> </p>

app/views/users/new.html.erb
<div class="page-header">
  <h1>Sign Up</h1>
</div>

<%= form_for @user , html: { multipart: true } do |f| %>
<% if @user.errors.any? %>
<div class="alert alert-danger">
  <strong>
    <%= pluralize(@user.errors.count, "error") %>
    prevented you from signing up:
  </strong>
  <ul>
    <% @user.errors.full_messages.each do |msg| %>
    <li><%= msg %></li>
    <% end %>
  </ul>
</div>
<% end %>

<div class="form-group">
  <%= f.label :name %>
  <%= f.text_field :name %>
</div>


<div class="form-group">
  <%= f.label :email %>
  <%= f.email_field :email, class: "form-control" %>
</div>

<div class="form-group">
  <%= f.label :password %>
  <%= f.password_field :password, class: "form-control" %>
</div>

<div class="form-group">
  <%= f.label :password_confirmation %>
  <%= f.password_field :password_confirmation,
  class: "form-control" %>
</div>

<div class="form-group">
  <%= f.label :avatar %>
  <%= f.file_field :avatar %>
</div>



<%= f.submit class: "btn btn-primary" %>
<% end %>